name: release_xgo

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release_xgo:
    uses: spywiree-priv/meta/.github/workflows/release_xgo.yml@main
    with:
      generate: false
