name: lint_base

on:
  workflow_call:
    inputs:
      generate:
        type: boolean
        required: false
      test:
        type: boolean
        required: false

jobs:
  golangci-lint:
    uses: spywiree/meta/.github/workflows/z_golangci-lint.yml@main
    with:
      generate: ${{ inputs.generate }}

  govulncheck:
    uses: spywiree/meta/.github/workflows/z_govulncheck.yml@main
    with:
      generate: ${{ inputs.generate }}

  ruleguard:
    uses: spywiree/meta/.github/workflows/z_ruleguard.yml@main
    with:
      generate: ${{ inputs.generate }}
      args: "-disable largeloopcopy"

  test:
    if: ${{ inputs.test }}
    uses: spywiree/meta/.github/workflows/z_test.yml@main
