name: release_xgo

on:
  workflow_call:
    inputs:
      pre_command:
        type: string
        required: false
      project_path:
        type: string
        default: "."
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["windows", "linux"]
        goarch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "go.mod"
          ldflags: "-s -w"
          build_flags: "-trimpath"
          sha256sum: true
          md5sum: false
          pre_command: ${{ inputs.pre_command }}
          project_path: ${{ inputs.project_path }}
