name: govulncheck

on:
  workflow_call:
    inputs:
      generate:
        type: boolean
        required: false

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - if: ${{ inputs.generate }}
        run: go generate ./...
        shell: bash
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash
      - run: govulncheck ./...
        shell: bash
