name: golangci-lint

on:
  workflow_call:
    inputs:
      generate:
        type: boolean
        required: false
      args:
        type: string
        required: false
        default: "--timeout=5m -Egosimple -Egovet -Eineffassign -Estaticcheck -Eunused -Egosec -Egocritic -Egosmopolitan -pperformance"

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - if: ${{ inputs.generate }}
        run: go generate ./...
        shell: bash
      - uses: golangci/golangci-lint-action@v6
        with:
          args: ${{ inputs.args }}
