name: test

on:
  workflow_call:
    inputs:
      generate:
        type: boolean
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - if: ${{ inputs.generate }}
        run: go generate ./...
        shell: bash
      - uses: robherley/go-test-action@v0
